### ISSUE TITLE
How to upgrade to the next TYPO3 version?

### ISSUE THREAD

**Issue by rowild** [GsTYPO3/ddev-typo3-src#7]
It would be great, it the repo could also describe how an upgrade an existing project to the next version of TYPO3 and pre-requisites as well as the consequences to be considered.

Simply changing the requirement in ddev's `config.yaml` does not seem to suffice.

This is what I did:

- Backup the DB with `ddev export --gzip=false --file=db_backup.sql`
- Run `ddev poweroff`
- Delete all `.yaml` files in the `.ddev` folder except for `config.yaml`
- Configure `config.yaml` with the new `TYPO3_MAJOR_VERSION` (10 in my case) (and adapt `TYPO3_MINOR_VERSION` if necessary)
- Run `ddev start`

At this point TYPO3's front is opened, and it throws an error pointing to the TYPO3 v10.4.21 resource:

```
Call to undefined method TYPO3\CMS\Core\Cache\Frontend\VariableFrontend::require()

in /var/www/html/typo3_src-10.4.21/typo3/sysext/core/Classes/Package/PackageManager.php line 207
```

However, when switching to the install tool, it shows that the just updated project is still running on TYPO3 v9.5.31.

I would have proceeded like this:

- Import database with `ddev import --src=db_backup.sql`
- Run Database update
- Run Updater

None of that makes any difference at this point. 

I am most likely doing something very very wrong here :-/

Any chance to provide the steps? I'd be happy to poor them in sentences and provide a PR for the documentation.

**Comment by gilbertsoft** [comment]
@rowild found the bug, the links are created wrong in case they already exist. This worked for me as temporary workaround until the script is fixed:

- stop the project `ddev stop`
- change `TYPO3_MAJOR_VERSION` in `.ddev/config.yaml`
- remove `htdocs/typo3_src`, `htdocs/typo3`, `htdocs/index.php` and `htdocs/typo3temp`
- enable the install tool `ddev exec touch htdocs/typo3conf/ENABLE_INSTALL_TOOL`
- start the project `ddev start`
- run the upgrade wizards in the install tool

**Comment by rowild** [comment]
Closing with PR #8

**Comment by rowild** [comment]
Ah, ok. Let me know when you need a tester.

One thing I observe is that the script always leads to the install tool. So whenever I stop the project at the end of the day (ddev stop) and start it the next day (without doing any updates, just simply starting it again to keep working on it), I will end up in the install tool. 
This is not a problem at all for me. It is just something that I observe. Usually, when I start working on a page, I open the backend, not the install toll.

**Comment by gilbertsoft** [comment]
Oh, forgot to add a closing statement to the PR #8 so I'm going to close it manualy now...
